#!/usr/bin/env bash
# Bash script that configures Nginx to redirect '/redirect_me' to 'http://youtube.com/'
# The redirection is configured as a "301 Moved Permanently"

apt-get update -y
apt-get install -y nginx

# Ensure web root exists
mkdir -p /var/www/html
echo "Holberton School" > /var/www/html/index.html

# Replace default Nginx config
cat > /etc/nginx/sites-available/default << 'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Restart Nginx to apply changes
service nginx restart

