#!/usr/bin/env bash
# Configures Nginx to add a custom X-Served-By header

apt-get update -y
apt-get install -y nginx

sed -i '/listen 80 default_server;/a\\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default

service nginx restart
