#!/usr/bin/env bash
# Installs and configures Nginx to serve the required page on port 80

set -e
export DEBIAN_FRONTEND=noninteractive

sudo apt-get update
sudo apt-get install  nginx

mkdir -p /var/www/html

printf 'Holberton School for the win!\ ' > /var/www/html/index.html

rm -f /etc/nginx/sites-enabled/default
cat > /var/www/html/index.html <<'HTML'
Holberton School
HTML


cat > /etc/nginx/sites-available/default <<'CONF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;
    
    location / {
        try_files $uri $uri/ =404;
    }
}
CONF


ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

nginx -t
service nginx restart || service nginx start


nginx -t
service nginx restart || service nginx start

curl 127.0.0.1
