#!/usr/bin/env bash
# Configures Nginx to serve a custom 404 page

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

# Redirect block from 3-redirection
sed -i '/listen 80 default_server;/a\
    location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default

# Custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i '/listen 80 default_server;/a\
    error_page 404 /404.html;' /etc/nginx/sites-available/default

service nginx restart
