#!/usr/bin/env bash
# Configures Nginx to serve a custom 404 page

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

sed -i '/listen 80 default_server;/a\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i '/listen 80 default_server;/a\\terror_page 404 /404.html;' /etc/nginx/sites-available/default

service nginx restart
